// ZuzabrGames All rights reserved 2024

#pragma once

#include "NativeGameplayTags.h"

namespace ColorDayGameplayTags
{
	/**Character Input Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);

	/**Weapon Input Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_SwitchAmmo);

	/**Player Ability**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Fire);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_SwitchAmmo);
	
	/**Weapon Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Gun);

	/**Player Event Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Gun);
}