// ZuzabrGames All rights reserved 2024

#pragma once

#include "NativeGameplayTags.h"

namespace ColorDayGameplayTags
{
	/**Character Input Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);

	/**Weapon Input Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_SwitchAmmo);

	/**Player Ability**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Fire);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_SwitchAmmo);
	
	/**Weapon Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Gun);

	/**Player Event Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Gun);

	/**Color Projectile Tag**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Red);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Grey);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Green);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Blue);

	/**Interactive Actor Ability*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_Activate);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_Deactivate);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_BecomeExplosive);

	/**Interactive Actor Tags*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_Active);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_Explosive);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_HasPhysics);

	/**Interactive Actor Instigators*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Instigator_Player);
	
}