// ZuzabrGames All rights reserved 2024

#pragma once

#include "NativeGameplayTags.h"

namespace ColorDayGameplayTags
{
	/**Character Input Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	

	/**Weapon Input Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_SwitchAmmo);


	/**Item Input Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Item_PutDown);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Item_Throw);

	/**Player Ability**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Fire);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_SwitchAmmo);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Item_PutDown);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Item_Throw);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Item_Grab);

	/**Character Ability**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Ability_Death);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Status_Dead);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Damage);

	/**NPC Ability**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_Ability_MeleeAttack);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_Ability_RangeAttack);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_Ability_GotDamage);

	/**NPC State**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Passive);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Passive_Patrol);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Passive_Hiding);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Investigate);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Dead);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Staggered);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Attack);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Attack_MeleeAttack);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_State_Attack_RangeAttack);

	
	/**Weapon Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Item);

	/**Player Event Tags**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Gun);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Gun);

	/**Color Projectile Tag**/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Red);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Grey);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Green);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Blue);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile_Yellow);

	/**Interactive Actor Ability*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_Activate);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_Deactivate);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_BecomeExplosive);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_TakeItem);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Ability_Interact);

	/**Interactive Actor Tags*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_Active);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_Explosive);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_HasPhysics);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_Grabbed);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_Locked);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Status_Opened);

	/**Interactive Actor Instigators*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Instigator_Player);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ColorActor_Instigator_NPC);

	/**Process tags*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Process_NeedUnequip);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Process_NeedEquipWeapon);
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Process_NeedEquipItem);
	
	/**Shared tags*/
	COLORDAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Damage);
}